apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'run.krolik.oxpulse.mesh'
    compileSdk rootProject.ext.compileSdkVersion
    defaultConfig {
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
}

dependencies {
    implementation project(':capacitor-android')
    implementation "androidx.appcompat:appcompat:$rootProject.ext.androidxAppCompatVersion"
    implementation "androidx.core:core-ktx:$rootProject.ext.androidxCoreVersion"
}
